spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sehrishf/app-configuration.git
          username: ${GIT_CONFIGSERVER_USER}
          password: ${GIT_CONFIGSERVER_TOKEN}
          clone-on-start: true
          default-label: main
          force-pull: true

server:
  port: 8888
