spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user,/api/user/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**,/api/cart/**
            # Eureka through Gateway
            - id: eureka-dashboard
              uri: http://localhost:8761
              predicates:
                - Path=/eureka
              filters:
                - SetPath=/
            - id: eureka-server-static
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: read-only
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
